from core.banner import VERSION, ORGANIZATION, AUTHOR

def display_about() -> None:
    print("\n" + "=" * 50)
    print("           CLI INFORMATION PAGE           ")
    print("=" * 50)
    print(f"  Application : Workstation CLI")
    print(f"  Version     : {VERSION}")
    print(f"  Author(s)   : {AUTHOR}")
    print(f"  Organization: {ORGANIZATION}")
    print("=" * 50)
    print("\n  Offline Chemistry Suite & Calculator Engine.")
    print("  Education First.")
    print("\n" + "=" * 50)
    # Credits section (added for v0.0.4)
    print("\nCREDITS:\n")
    print("  - Local model support: Ollama")
    print("  - Models: Mistral, Gemma, and other community projects")
    print("  - Project: Workstation CLI — Workable Projects / Dutchh")
    print("\nFor more info or links, see the project README.")
    input("\nPress ENTER to return to the main menu...")
